wandb_version: 1

fold:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1719983449.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      3:
      - 13
      - 16
      - 23
      - 60
      4: 3.8.18
      5: 0.16.6
      6: 4.41.2
      8:
      - 2
      - 5
      9:
        2: lightning_fabric_logger
      13: linux-x86_64
