#--------------------- config v37
# => learning rate scheduler 
#---------------------


#-------------------------------- This is Test Configuration
# Version 
RUN_VERSION : 39

# Data Type 
DATA_TYPE : alldata #streetview #topview

# K-fold
N_SPLIT: 5
RANDOM_STATE: 99

# DDP                
FABRIC: True
DEVICES: [0,1,2,3]
NUM_WORKERS: 8

# Single run 
DEVICE: cuda:0

# SAMPLE
SAMPLE : False # Data sampling for test 
SAMPLE_PERCENT : 0.01


# MODEL
TIMM: True
MODEL: eva02_base_patch14_448.mim_in22k_ft_in22k_in1k #VAN #eva_large_patch14_336.in22k_ft_in22k_in1k
SAVE_DIR: /mnt/hdd/eric/.tmp_ipy/15.Lab_Detection/07.Challenge/01.MapYourCity_HuggingFace/output

# TRAIN
LOSS_FN : CE # label smoothing 넣어봄 !=> 나중에 수정  
CLASSES_NUM : 7
INTERPOLATION: bicubic
EPOCHS: 16                   # number of epochs to train
BATCH_SIZE: 4            # batch size to use
EVAL_INTERVAL: 1            # evaluation interval
LR : 0.0002
# scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(optimizer, T_0=2, T_mult=1, eta_min=cfg.LR,gamma=0.5)


#LR: 2.46374944022223E-05 # lr = (batch_size / 1024) * 1e-3
# learnign rate 보완 절실함. 

# AUGMENTATION
AUGMENTATIONS: ["griddropout", "horizontalflip", "verticalFlip", "blur", "gaussnoise"]

# LABEL Distribution
LABEL_DEVIATION : 2 