wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1719843643.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      3:
      - 7
      - 23
      - 60
      4: 3.8.18
      5: 0.16.6
      6: 4.41.2
      8:
      - 2
      - 5
      9:
        2: lightning_fabric_logger
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: iteration
      5: 1
      6:
      - 1
    - 1: progress
      5: 1
      6:
      - 1
    - 1: time_remaining
      5: 1
      6:
      - 1
    - 1: time_total
      5: 1
      6:
      - 1
    - 1: loss
      5: 1
      6:
      - 1
    - 1: batch_size
      5: 1
      6:
      - 1
    - 1: lr
      5: 1
      6:
      - 1
    - 1: train precision
      5: 1
      6:
      - 1
    - 1: train recall
      5: 1
      6:
      - 1
    - 1: train f1
      5: 1
      6:
      - 1
    - 1: train accuracy
      5: 1
      6:
      - 1
